### ISSUE TITLE
Impossible to use existing marker on marker

### ISSUE THREAD

**Issue by gquemener** [prolic/fpp#65] opened 2018-06-13 10:42 UTC
# Scenario

Given the following "domain.fpp":
```
namespace App;
marker Person : \App\User;
```
and the following existing marker:
```php
<?php

declare (strict_types = 1);

namespace App;

interface User
{
}
```
When I run the fpp command
Then the "src/Person.php" file should contain:
```php
<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace App;

interface Person extends \App\User
{
}
```

# Result

This scenario fails with the following error:
```
Exception: Marker App\Person cannot extend unknown marker App\User
```

# Fix
Switch the autoloader flag to true [on this `interface_exists` function call](https://github.com/prolic/fpp/blob/2bfadfb1c67ca875bb3d9757a105c52fc6f82efa/src/builder/buildClassExtends.php#L54).

**Comment by prolic** [comment] 2018-06-13 11:34
Duplicate of #66

**Comment by gquemener** [comment] 2018-06-13 16:05
Well, technically it was not a duplicate. One was related to marking data (#66), while this one is related to extending marker.

I'm working on a fix.

**Closed** 2018-06-13 16:30 UTC
